Add docs & tests for Table.set_format
data-8/datascience pull request #457
Opened 2020-09-13 22:29 UTC by hmstepanek

- [ ] Add docs & tests for Table.set_format

This is a partial fix for [Add documentation](https://github.com/data-8/datascience/issues/163) as it adds documentation for Table.set_format.

2020-09-13 23:31 UTC, adnanhemani requested changes
Thanks for this! Just a few comments

2020-09-13 23:31 UTC, adnanhemani commented on datascience/tables.py
> -                    else:
Typo?

2020-09-13 23:31 UTC, adnanhemani commented on datascience/tables.py
> +        """
Could you please add an example of one of the built-in formatter classes near the top of this docstring? Most of the users of our library, I image, would be using these quite frequently.

2020-09-14 06:07 UTC, hmstepanek commented
I've made the first example use the builtin CurrencyFormatter and also made the custom formatter examples more relatable since the builtin CurrencyFormatter would not be able to handle these cases (since it always prepends the symbol). Also fixed the typo.

2020-09-25 22:54 UTC, adnanhemani approved these changes
Nice work - thanks for making this documentation so detailed!

2020-09-25 22:54 UTC, merged