Updated documentation for two remaining transformation methods
data-8/datascience pull request #472
Opened 2020-10-04 12:06 UTC by CodTan

[ ] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Updated documentation and added examples within docstrings of `pivot_bin()` and `stack()` transformation methods.
For `pivot_bin()`, passing the argument `normed=True` responds with a Table and the following warning:
```
.../datascience/tables.py:1156: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  _, rbins = np.histogram(self[value_column],**vargs)
.../datascience/tables.py:1163: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  counts,_ = np.histogram(col_vals,**vargs)
```
Passing the argument `density=True` along with `normed=True` however results in a Table with no warnings.

Due to this, examples specific to `normed=True` for `pivot_bin()` method have not been included in this PR.

2020-10-04 13:55 UTC, CodTan commented
Need help! Not sure why the build is failing! :/

2020-10-05 04:10 UTC, SambhaviPD commented
@CodTan , Not sure whether it helps, but noticed the following in your travis build,

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
During handling of the above exception, another exception occurred:
URLError                                  Traceback (most recent call last)

2020-10-05 04:59 UTC, CodTan commented
@SambhaviPD Yes, I did check that. Since the issues were with tests/Maps.ipynb and test_read_table, I couldn't understand what to do with them.
Thanks anyway!

2020-10-07 03:35 UTC, adnanhemani commented
I've refreshed the cache and the tests shouldn't be failing anymore. Let's give it another try - please push a dummy change to tell Travis to rebuild this branch :)

2020-10-07 06:13 UTC, CodTan commented
Thanks a ton @adnanhemani. The build is successful now. :)

2020-10-07 06:33 UTC, adnanhemani requested changes
This looks great! 🎉 Just 2 small cosmetic changes required and then we should be good to go!

2020-10-07 06:33 UTC, adnanhemani commented on datascience/tables.py
> +        ...     'column3':'b',
Can we please get these all lined up on the same indent level?

2020-10-07 06:33 UTC, adnanhemani commented on datascience/tables.py
> +	...   {
Same as above - please fix the indentation levels :)

2020-10-07 07:19 UTC, CodTan commented
Fixed the issues as suggested! :)

2020-10-07 07:34 UTC, davidwagner commented
The Travis build is failing, complaining about tables.py:1801, the doctests under pivot_bin(): `SyntaxError: closing parenthesis '}' does not match opening parenthesis '('`.  I confess I don't understand the error message.

2020-10-07 07:59 UTC, CodTan commented
@davidwagner, fixed the error. The build is successful now.

2020-10-08 08:19 UTC, adnanhemani approved these changes
Look great! Thanks so much! :D

2020-10-08 08:19 UTC, merged