Add pythonic aliases for comparison predicates.
data-8/datascience pull request #553
Opened 2022-09-08 20:25 UTC by SirTZN

[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Add pythonic aliases for comparison predicates.
Ex: added `are.greater_than` as an alias of `are.above`

2022-09-12 04:55 UTC, davidwagner commented
Can you help me understand the rationale for why this addition is needed/beneficial?

2022-09-12 18:13 UTC, SirTZN commented
I would also like to add that this is the notation already used in the some of the function's descriptions.
Snippet from predicates.py:

```python
@staticmethod
def above(y):
    """Greater than y."""
```

2022-12-23 21:49 UTC, adnanhemani requested changes
I can agree to seeing that this might be beneficial and it's great that it's just adding a simple alias, so there's no code maintainability issues. I just want to ensure that code testing coverage isn't hit as a result of this new code, so can we please add some testing code around the new methods?

Once we have the testing code, I can merge this in, it's in great condition. Thanks!

2022-12-31 17:01 UTC, SirTZN commented
I added methods replicating the existing ones. I've never worked with pytest, however, so please do let me know if anything needs to be amended.

2023-01-01 23:55 UTC, adnanhemani requested changes
Hey, this is very close to being mergable - thank you! You should be able to see updated coverage when you push new commits now.

2023-01-01 23:55 UTC, adnanhemani commented on CHANGELOG.md
> +* Add alias tests to test_predicates.py
We don't need this line. Just the first one is fine :)

2023-01-01 23:55 UTC, adnanhemani commented on datascience/predicates.py
> +        return are.below_or_equal_to(y)
Based on: https://coveralls.io/builds/55559799/source?filename=datascience%2Fpredicates.py

We're missing test coverage on this method and a few others. The tests you've created are fantastic so far, if you could please add a few more for the missing test methods - this should be mergeable!

2025-10-07 08:13 UTC, adnanhemani commented
Closing due to inactivity.

2025-10-07 08:13 UTC, closed without merging