Appended to docu-string for function make_array and updated function …
data-8/datascience pull request #588
Opened 2023-05-26 17:24 UTC by stevenworks

[ ] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Added args and return type to docu-string for function make_array. Also updated function sample_proportions to use multinomial method of Generator class per Numpy recommendations: https://numpy.org/doc/stable/reference/random/generated/numpy.random.multinomial.html

2023-05-27 00:05 UTC, adnanhemani requested changes
Overall, looks good - thanks for these changes! Please revise as per the comments and then it should be good to merge. Thanks!

2023-05-27 04:48 UTC, stevenworks commented on datascience/util.py
> +plt.rcParams['patch.force_edgecolor'] = True
The use of single quotes maintains consistency with the rest of the codebase where single quotes are used. Honestly, maybe not necessary but might as well.

2023-05-27 04:49 UTC, stevenworks commented on datascience/util.py
> -    return False
I apologize for missing that.

2023-05-27 04:49 UTC, stevenworks commented on datascience/util.py
> +        ``sd`` (numeric): standard deviation of normal distribution
I missed this minor error as well.

2023-06-06 09:39 UTC, adnanhemani approved these changes
Thanks for making the requested changes - a quality PR! :D

2023-06-06 09:39 UTC, adnanhemani commented on datascience/util.py
> +plt.rcParams['patch.force_edgecolor'] = True
Fair enough. Let's leave your changes then :)

2023-06-06 09:39 UTC, adnanhemani commented on datascience/util.py
> -    return False
Thanks for this change :)

2023-06-06 09:40 UTC, merged