Increase the test coverage of maps.py in test_maps.py
data-8/datascience pull request #603
Opened 2023-10-31 12:32 UTC by NhienPhan2909

[x] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Try to increase the test coverage of maps.py to as close to 100% as possible.

2023-11-04 23:11 UTC, adnanhemani requested changes
Thank you for this - this is very needed.

But the unit tests are failing. Can you please take a look at the unit test results on this PR? It may help you to run the tests locally first to ensure that the tests aren't failing when you push to the PR. Please let me know if you have any questions - thank you!

2023-11-04 23:11 UTC, adnanhemani commented on tests/test_maps.py
> +    updated_geojson = region.geojson("new_id")
Isn't the new id named "test_id" above? Am I missing something?

2023-12-19 06:24 UTC, adnanhemani approved these changes
After making the requested changes myself, this now looks good to me. But since I've done non-trivial work on this PR, I'd request @davidwagner to please review this first. I'll try to fill in the remaining untested code in a separate PR once this merges.

2023-12-19 06:24 UTC, adnanhemani commented on tests/test_maps.py
> +    updated_geojson = region.geojson("new_id")
Didn't understand the code earlier, makes sense now.

2023-12-26 05:53 UTC, davidwagner approved these changes

2023-12-26 05:55 UTC, davidwagner commented
This looks good to me!  Thank you.  I appreciate all the tests and the bugfix in Map.read_geojson().  (Side note: I never noticed the semantics of Map.overlay(Map) before...)

2023-12-26 05:55 UTC, merged

2023-12-26 05:55 UTC, davidwagner commented
@adnanhemani Merged.  Thank you for the review!