added a tutorial for the Maps module
data-8/datascience pull request #605
Opened 2023-12-17 10:43 UTC by ShuaibNuruddin

This pull request addresses issue #390 by introducing a tutorial for the maps module. I welcome feedback to enhance the clarity and effectiveness of the tutorial content.

2023-12-18 03:34 UTC, adnanhemani requested changes
Very nicely done! Just the one minor comment and then we should be ready to merge and deploy.

2023-12-18 03:34 UTC, adnanhemani commented on docs/tutorial.rst
> +The main class in the maps module is the Map class. In this code we create a default map. Maps can be displayed or converted to html.
"In this code we create a default map" -> "In this code we create a default Map" (to distinguish against Python maps)

2023-12-18 14:15 UTC, ShuaibNuruddin commented
Thank you for your feedback. I have changed it from map to Map.

2023-12-19 06:16 UTC, adnanhemani approved these changes

2023-12-19 06:16 UTC, merged

2023-12-19 06:17 UTC, adnanhemani commented
Just merged! Once again, amazing job on this - looking forward to future contributions :)